//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicManager()
        {
            this.ClinicDoctors = new HashSet<ClinicDoctor>();
        }
    
        public int ClinicManagerId { get; set; }
        public int ClinicUserId { get; set; }
        public int ClinicFloor { get; set; }
        public int MaxNumOfDoctorsSupervised { get; set; }
        public int MinNumOfRoomSupervised { get; set; }
        public Nullable<int> NumberOfMistake { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicDoctor> ClinicDoctors { get; set; }
        public virtual ClinicUser ClinicUser { get; set; }
    }
}
