//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicDoctor
    {
        public int ClinicDoctorId { get; set; }
        public int ClinicUserId { get; set; }
        public int UniqueNumber { get; set; }
        public int BancAccount { get; set; }
        public int DepartmentId { get; set; }
        public int WorkShiftId { get; set; }
        public bool InChargeOfAdmission { get; set; }
        public int ClinicManagerId { get; set; }
    
        public virtual ClinicUser ClinicUser { get; set; }
        public virtual ClinicManager ClinicManager { get; set; }
        public virtual Department Department { get; set; }
        public virtual Workshift Workshift { get; set; }
    }
}
