//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int InstitutionId { get; set; }
        public Nullable<System.DateTime> BuildDate { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public string Address { get; set; }
        public int NumberOfFloors { get; set; }
        public int NumberOfRoomsPerFloor { get; set; }
        public bool Terrace { get; set; }
        public bool Backyard { get; set; }
        public int AccessPointsForAmbulances { get; set; }
        public int AccessPointsForhandicaps { get; set; }
        public int ClinicUserId { get; set; }
    
        public virtual ClinicUser ClinicUser { get; set; }
    }
}
