//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMedical
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicaClinicEntities1 : DbContext
    {
        public MedicaClinicEntities1()
            : base("name=MedicaClinicEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClinicDoctor> ClinicDoctors { get; set; }
        public virtual DbSet<ClinicMaintenance> ClinicMaintenances { get; set; }
        public virtual DbSet<ClinicManager> ClinicManagers { get; set; }
        public virtual DbSet<ClinicPatient> ClinicPatients { get; set; }
        public virtual DbSet<ClinicUser> ClinicUsers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Workshift> Workshifts { get; set; }
    }
}
