//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicMedical
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoctor
    {
        public int ClinicUserId { get; set; }
        public string FullName { get; set; }
        public int IDNumber { get; set; }
        public int GenderId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public bool IsDeleted { get; set; }
        public string DepartmanName { get; set; }
        public string WorkShiftName { get; set; }
        public int ClinicManagerId { get; set; }
        public int WorkShiftId { get; set; }
        public bool InChargeOfAdmission { get; set; }
        public int DepartmentId { get; set; }
        public long BancAccount { get; set; }
        public int UniqueNumber { get; set; }
        public int ClinicDoctorId { get; set; }
    }
}
